name: update.sh

permissions:
  # Git push permissions are needed
  contents: write

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '11 0 * * *'
  workflow_dispatch:

jobs:
  run_update_sh:
    name: Run update.sh script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WOKFLOW_TOKEN }}
    - name: Run update.sh script
      run: ./update.sh
    - name: Commit files
      run: |
        git config --local user.email "workflow@github.com"
        git config --local user.name "GitHub Workflow"
        git switch -C changes-from-update.sh
        git add -A
        git commit -m "Update roundcube version (via update.sh)" || echo "Nothing to update"
        git push --force-with-lease origin
    - name: Create Pull Request
      run: gh pr create -B master -H changes-from-update.sh --title 'Changes from update.sh' --assignee pabzm
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
